#!/bin/bash
# amalgamate.sh — Generate a single-file Cynk SDK build (Mosquitto platform).
#
# Output:
#   dist/cynk.h                — standalone public header (types inlined)
#   dist/cynk_amalgamation.c   — all SDK source in one file
#
# Usage on RPi / desktop:
#   gcc main.c cynk_amalgamation.c -lmosquitto -lssl -lcrypto -o firmware
#
# This script does NOT affect Arduino, ESP-IDF, or PlatformIO builds — those
# platforms use their own library management systems.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$REPO/dist"

mkdir -p "$DIST"

# ---- Helper: strip local #include "..." lines from a file ----
strip_local_includes() {
  sed '/^#include "[^"]*"/d' "$1"
}

# ---- Helper: extract body from a header (strip guards, system includes,
#      extern-C wrapper, and the leading doc-comment block). Keeps all type
#      definitions, inline comments, and code intact. ----
extract_header_body() {
  awk '
    BEGIN { in_top_comment=0; past_top_comment=0; in_extern_c=0 }

    # Skip include guard open/close
    /^#ifndef [A-Z_]+_H$/ { next }
    /^#define [A-Z_]+_H$/ { next }
    /^#endif \/\* [A-Z_]+_H \*\/$/ { next }

    # Skip system includes
    /^#include </ { next }

    # Skip local includes
    /^#include "/ { next }

    # Track and skip the leading doc-comment block (/* ... */)
    !past_top_comment && /^\/\*/ { in_top_comment=1; next }
    in_top_comment && /\*\// { in_top_comment=0; past_top_comment=1; next }
    in_top_comment { next }

    # Skip extern "C" open block
    /^#ifdef __cplusplus$/ { next }
    /^extern "C" \{$/ { next }

    # Skip extern "C" close: bare } on its own line
    /^\}$/ { next }

    # Skip bare #endif (from extern-C conditionals)
    /^#endif$/ { next }

    { past_top_comment=1; print }
  ' "$1"
}

# ============================================================================
# 1. Generate standalone cynk.h (types inlined)
# ============================================================================
{
  cat <<'EOF'
#ifndef CYNK_H
#define CYNK_H

/*
 * Cynk Device SDK — public API (standalone header)
 * https://cynk.tech
 *
 * AUTO-GENERATED by scripts/amalgamate.sh — do not edit manually.
 *
 * Connect to cynk.tech and send telemetry in three lines:
 *
 *   cynk_device *dev = cynk_connect("my_device", "my_password");
 *   cynk_send(dev, "temperature", 25.5);
 *   cynk_disconnect(dev);
 */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
EOF

  # Inline type definitions from cynk_types.h
  extract_header_body "$REPO/src/internal/cynk_types.h"

  # Inline public API declarations from cynk.h
  extract_header_body "$REPO/include/cynk.h"

  cat <<'EOF'

#ifdef __cplusplus
}
#endif

#endif /* CYNK_H */
EOF
} > "$DIST/cynk.h"

# ============================================================================
# 2. Generate cynk_amalgamation.c
# ============================================================================
{
  cat <<'EOF'
/*
 * Cynk SDK — Amalgamation Build (Mosquitto platform)
 * https://cynk.tech
 *
 * AUTO-GENERATED by scripts/amalgamate.sh — do not edit manually.
 *
 * Compile with:
 *   gcc main.c cynk_amalgamation.c -lmosquitto -lssl -lcrypto -o firmware
 */

#define _POSIX_C_SOURCE 200112L

/* ---- System includes ---- */
#include <stddef.h>
#include <stdint.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <mosquitto.h>

/* ---- Public header ---- */
#include "cynk.h"
EOF

  echo ""
  echo "/* ==== jsmn.h (inline) ==== */"
  strip_local_includes "$REPO/third_party/jsmn/jsmn.h"

  echo ""
  echo "/* ==== cynk_protocol.h (internal) ==== */"
  strip_local_includes "$REPO/src/internal/cynk_protocol.h"

  echo ""
  echo "/* ==== cynk_platform.h (internal) ==== */"
  strip_local_includes "$REPO/src/internal/cynk_platform.h"

  echo ""
  echo "/* ==== jsmn.c ==== */"
  strip_local_includes "$REPO/third_party/jsmn/jsmn.c"

  echo ""
  echo "/* ==== cynk_protocol.c ==== */"
  strip_local_includes "$REPO/src/cynk_protocol.c"

  echo ""
  echo "/* ==== mqtt_mosquitto.c ==== */"
  strip_local_includes "$REPO/src/platform/mqtt_mosquitto.c"

  echo ""
  echo "/* ==== cynk.c ==== */"
  strip_local_includes "$REPO/src/cynk.c"
} > "$DIST/cynk_amalgamation.c"

echo "Generated:"
echo "  $DIST/cynk.h"
echo "  $DIST/cynk_amalgamation.c"
echo ""
echo "Usage:"
echo "  gcc main.c dist/cynk_amalgamation.c -lmosquitto -lssl -lcrypto -o firmware"
